name: Trigger Website Workflow

on:
  push:
    branches:
      - main

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Set Dynamic Date
        id: date
        run: echo "current_date=$(date '+%Y-%m-%d')" >> $GITHUB_ENV

      - name: Trigger Website Repository Workflow
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.PAT_FOR_WEBSITE_REPO }}" \
            https://api.github.com/repos/winzamark123/portfolio-website/dispatches \
            -d '{"event_type": "${{ env.current_date }} update blog"}'
